export const upliftInsightsSnapshot = {
  header: {
    eyebrow: "Phase 4 model-based uplift analysis",
    title: "The DRLearner ranking concentrates the strongest response in a few high-value pockets.",
    description:
      "This screen is a static rendering of the saved Phase 4 uplift artifacts. It shows who rises to the top, where suppression starts to matter, and how cleanly the ranking behaves across deciles.",
  },
  modelState: {
    modelName: "DRLearner conversion",
    validationVerdict: "promising_but_noisy",
    overallObservedAte: 0.9977,
    topDecileGain: 2.6759,
    upliftConcentrationRatio: 3.68,
    monotonicityBreakCount: 3,
  },
  deciles: [
    { rank: 1, uplift: 3.6735, tone: "positive" },
    { rank: 2, uplift: 4.0185, tone: "positive" },
    { rank: 3, uplift: 1.2346, tone: "positive" },
    { rank: 4, uplift: 0.0363, tone: "positive" },
    { rank: 5, uplift: -0.9857, tone: "negative" },
    { rank: 6, uplift: 0.7846, tone: "positive" },
    { rank: 7, uplift: 0.5415, tone: "positive" },
    { rank: 8, uplift: 0.3735, tone: "positive" },
    { rank: 9, uplift: -0.504, tone: "negative" },
    { rank: 10, uplift: 1.1346, tone: "positive" },
  ],
  segmentTable: [
    {
      segment: "High Intent Returners",
      meanPredictedEffect: 2.2911,
      observedAte: 2.4331,
      positiveEffectShare: 76.31,
      action: "prioritize",
    },
    {
      segment: "Bargain Hunters",
      meanPredictedEffect: 1.5572,
      observedAte: 2.3197,
      positiveEffectShare: 95.04,
      action: "prioritize",
    },
    {
      segment: "Young Professionals",
      meanPredictedEffect: 1.2843,
      observedAte: 1.5375,
      positiveEffectShare: 86.51,
      action: "prioritize",
    },
    {
      segment: "Students",
      meanPredictedEffect: 0.8761,
      observedAte: 0.9512,
      positiveEffectShare: 97.46,
      action: "prioritize",
    },
    {
      segment: "Window Shoppers",
      meanPredictedEffect: 0.8478,
      observedAte: 0.0016,
      positiveEffectShare: 98.99,
      action: "watch",
    },
    {
      segment: "Families",
      meanPredictedEffect: 0.6968,
      observedAte: 0.1561,
      positiveEffectShare: 81.9,
      action: "watch",
    },
    {
      segment: "Loyal Members",
      meanPredictedEffect: 0.3909,
      observedAte: 0.0972,
      positiveEffectShare: 61.13,
      action: "watch",
    },
    {
      segment: "Lapsed Users",
      meanPredictedEffect: 0.0207,
      observedAte: -0.8005,
      positiveEffectShare: 68.82,
      action: "suppress",
    },
  ],
  topResponders: [
    {
      label: "Hackney",
      context: "borough",
      predicted: 2.6189,
      observed: 1.6326,
    },
    {
      label: "Merton",
      context: "borough",
      predicted: 2.5689,
      observed: 4.3005,
    },
    {
      label: "generic_search",
      context: "channel",
      predicted: 1.5259,
      observed: 3.5392,
    },
  ],
  suppressionWatch: [
    {
      label: "Lapsed Users",
      context: "segment",
      predicted: 0.0207,
      observed: -0.8005,
    },
    {
      label: "app_entry",
      context: "channel",
      predicted: 0.519,
      observed: -2.3934,
    },
    {
      label: "Camden",
      context: "borough",
      predicted: 0.7429,
      observed: -2.9281,
    },
  ],
  notes: [
    "Top deciles 1 and 2 materially outperform the overall baseline.",
    "Deciles 5 and 9 go negative, so the ranking already exposes real suppression zones.",
    "The ordering is not perfectly monotonic, which is why the saved validation verdict remains promising_but_noisy.",
  ],
} as const;
